apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-delete
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: elasticsearch-operator
      restartPolicy: Never
      containers:
        - name: pre-delete-job
          image: {{ .Values.deployConfig.imageRepo}}/{{ .Values.kubectlImage }}
          args: ["/bin/sh","-c","kubectl patch elasticsearches.es.k8s.io {{ .Values.elasticsearch.name  }} -n {{ .Release.Namespace }} --type json --patch='[{\"op\": \"remove\", \"path\": \"/metadata/finalizers\"}]' && kubectl delete elasticsearches.es.k8s.io {{ .Values.elasticsearch.name  }} -n {{ .Release.Namespace }}"]
