apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: elasticsearch-psp
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - emptyDir
  - gitRepo
  - hostPath
  - configMap
  - downwardAPI
  - projected
  - persistentVolumeClaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: podsecuritypolicy
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - default
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - default
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2022-09-27T09:05:43Z"
  name: podsecuritypolicy
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podsecuritypolicy
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
