apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: monitoring-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-operator
  template:
    metadata:
      labels:
        app: monitoring-operator
    spec:
      serviceAccountName: monitoring-operator
      containers:
      - image: {{ .Values.deployConfig.imageRepo }}/{{ .Values.monitoringOperator.image }}
        name: monitoring-operator
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        args:
        - -namespace={{ .Release.Namespace }}
        - "-v=3"
        - "-configmap=monitoring-config"
        - "-logtostderr=true"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
