apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-operator-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-operator-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: monitoring-operator
  namespace: {{ .Release.Namespace }}
